import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Collect the Tailwind class names that `@mulmocast/deck` and `mulmocast` emit, and write
 * them into a CSS file as `@source inline(...)`.
 *
 * Tailwind cannot find them on its own: the classes live as STRINGS inside compiled
 * JavaScript under node_modules, which Tailwind skips because it honours .gitignore — an
 * `@source` pointing straight at those directories generates nothing, which is how this was
 * found. `@source inline(...)` is the documented way to name classes that no file scan will
 * reach.
 *
 * Over-collecting is safe and under-collecting is not: a class that is not really a utility
 * generates nothing, while a missing one renders a beat unstyled. The pattern below is
 * deliberately loose for that reason.
 */
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const SOURCES = ["node_modules/@mulmocast/deck/lib", "node_modules/mulmocast/lib/utils/beat_html", "node_modules/mulmocast/lib/utils/image_plugins"];

const jsFiles = (dir: string): string[] => {
  let out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) out = out.concat(jsFiles(path));
    else if (path.endsWith(".js")) out.push(path);
  }
  return out;
};

// Class-like tokens anywhere in the file, bounded by a quote, backtick or whitespace.
//
// Two forms have to be caught and neither is reachable by scanning `class="..."` alone:
// deck stores `default: "text-[60px]"` in a lookup table and builds the attribute at
// runtime, and it also emits whole markup templates where splitting the literal on
// whitespace leaves tokens like `opacity-10"></div>`. Both were found by rendering real
// beats and diffing their classes against this list — see test_fragment_classes.ts.
//
// Over-collecting is safe: a token that is not a utility generates no rule. Under-collecting
// is not: a missing class renders a beat unstyled, with nothing to show it happened.
const CLASS_TOKEN = /(?<=["'`\s])-?[a-zA-Z][\w:./-]*(?:\[[^\]\s"'`]+\])?[\w:./\]%-]*(?=["'`\s>])/g;

const classes = new Set<string>();
for (const source of SOURCES) {
  const dir = join(root, source);
  try {
    statSync(dir);
  } catch {
    console.error(`missing: ${source} — is it installed?`);
    process.exit(1);
  }
  for (const file of jsFiles(dir)) {
    for (const match of readFileSync(file, "utf8").matchAll(CLASS_TOKEN)) classes.add(match[0]);
  }
}

const sorted = [...classes].sort();
const out = join(root, "src", "fragment-classes.css");
writeFileSync(
  out,
  `/* Generated by scripts/collect_fragment_classes.ts — do not edit.
   The classes @mulmocast/deck and mulmocast emit from compiled JS, which Tailwind's file
   scan cannot see (node_modules is gitignored). Regenerated by \`yarn build:css\`. */
@source inline("${sorted.join(" ")}");
`,
);
console.log(`${sorted.length} classes → src/fragment-classes.css`);
